server:
  port: 5000
  servlet:
    context-path: /review-service
spring:
  datasource:
    password: trinhvantung
    url: jdbc:postgresql://localhost:5432/bookstore_review
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    show-sql: true
security:
  oauth2:
    client:
      clientId: server
      clientSecret: secret
      grantType: client_credentials
      scope: server